[package]
name = "filehandler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascon = "0.4.0"
rs_sha256 = "0.1.3"
sha1 = "0.10.6"

